---
- hosts: all
  become: yes
  vars:
    group_name: "minio"
    user_name: "minio"
  tasks:
    - name: create group
      group:
        name: "{{ group_name }}"
        state: present

    - name: create user
      user:
        name: "{{ user_name }}"
        group: "{{ group_name }}"
    
    - name: add disk with label
      command: mkfs.xfs /dev/sdb -L DISK1

    - name: create folder minio data
      file:
        path: /mnt/disk1
        state: directory
    
    - name: change ownership folder
      file:
        path: /mnt/disk1
        owner: "{{ user_name }}"
        group: "{{ group_name }}"   
    
        - name: Add disk to fstab
        lineinfile:
        path: /etc/fstab
        line: "LABEL=DISK1      /mnt/disk1     xfs     defaults,noatime  0       2"
        insertbefore: BOF

        - name: mount disk
        command: mount -a
      
    - name: Get minio binary
      get_url:
        url: https://dl.min.io/server/minio/release/linux-amd64/minio
        validate_certs: no
        dest: /home/administrator/
        # use_proxy: yes
      # environment: "{{ proxy_env }}"

    - name: change ownership folder minio
      file:
        path: /home/administrator/minio
        state: file
        mode: 0755

    - name: move file binary
      command: mv /home/administrator/minio /usr/local/bin/

    - name: copy systemd minio
      template:
        src: ./files/minio.service.j2
        dest: /etc/systemd/system/minio.service
        
    - name: add local domain
      template:
        src: ./files/hosts.j2
        dest: /etc/hosts
    
    - name: copy env minio
      template:
        src: ./files/minio.j2
        dest: /etc/default/minio

    - name: enable and start minio
      systemd:
        name: minio
        state: started
        enabled: yes

    - name: start minio 
      systemd:
        state: started
        name: minio
    
